name: "申请加入"
description: "申请加入 LingmoOS Development Team (简体中文)"
title: "[加入申请]"
body:
  - type: markdown
    attributes:
      value: |
        如果您想加入 LingmoOS Development Team，请填写下方表单。申请提交后，我们将会在 72 小时内处理。
        另请注意，我们可能会要求您提交更多信息。因此，请关注您的 GitHub 绑定邮箱通知。
  - type: input
    id: qq-id
    attributes:
      label: QQ号（可选）
      placeholder: "例: 10000"
  - type: textarea
    id: reason
    attributes:
      label: 为什么想加入 LingmoOS Development Team？
      placeholder: "请简单说明您的原因（如果是被邀请进来请标注是谁邀请的）"
    validations:
      required: true
  - type: textarea
    id: introduce_yourself
    attributes:
      label: 介绍一下你自己
      placeholder: "例: 你的编程技能 (C++, Python等)"
    validations:
      required: true
